version: '3.3'

services:
  note:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: note
    command: ['/bin/sh', '-c', 'npm start']
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8083:8083
    networks:
      - capju
    env_file:
      - .env

networks:
  capju:
    external: true
